"""Read-outs: ranking, discrimination, calibration, interaction and resampling."""

from __future__ import annotations

from oaer.readings.discrimination import (
    Concordance,
    auprc,
    brier_score,
    calibration_slope,
    concordance_index,
    expected_calibration_error,
    net_benefit,
    net_benefit_advantage,
    net_reclassification_improvement,
    time_dependent_auroc,
)
from oaer.readings.interference import (
    InteractionRow,
    TercileGain,
    build_interaction_row,
    exposure_tercile_summary,
    interaction_beyond_additive,
    interaction_ratio,
    normalised_gain,
    ratio_admissible,
)
from oaer.readings.ranking import (
    average_precision,
    hits_at_k,
    hits_table,
    jaccard,
    mean_jaccard_across_sets,
    ndcg_at_k,
    ndcg_table,
    precision_at_k,
    recall_at_k,
    seed_dispersion,
    top_k_set,
)
from oaer.readings.resampling import (
    BootstrapResult,
    bootstrap_contrast,
    delta_with_interval,
    interval_half_width,
    one_sample_seed_test,
    paired_seed_test,
    pooled_site_interval,
    site_indices,
    site_stratified_bootstrap,
)

__all__ = [
    "BootstrapResult",
    "Concordance",
    "InteractionRow",
    "TercileGain",
    "auprc",
    "average_precision",
    "bootstrap_contrast",
    "brier_score",
    "build_interaction_row",
    "calibration_slope",
    "concordance_index",
    "delta_with_interval",
    "expected_calibration_error",
    "exposure_tercile_summary",
    "hits_at_k",
    "hits_table",
    "interaction_beyond_additive",
    "interaction_ratio",
    "interval_half_width",
    "jaccard",
    "mean_jaccard_across_sets",
    "ndcg_at_k",
    "ndcg_table",
    "net_benefit",
    "net_benefit_advantage",
    "net_reclassification_improvement",
    "normalised_gain",
    "one_sample_seed_test",
    "paired_seed_test",
    "pooled_site_interval",
    "precision_at_k",
    "ratio_admissible",
    "recall_at_k",
    "seed_dispersion",
    "site_indices",
    "site_stratified_bootstrap",
    "time_dependent_auroc",
    "top_k_set",
]
